export const QUERIES = {
  getCollections: 'getCollections',
  getCollectionNFTs: 'getCollectionNFTs',
  getNfts: 'getNfts',
  getAllNFts: 'getAllNFts',
  getSingleNft: 'getSingleNft',
  getUserNfts: 'getUserNfts',
  getCollectionDetails: 'getCollectionDetails',
  getAllCollectionNfts: 'getAllCollectionNfts',
  getUser: 'getUser',
  getUserActivity: 'getUserActivity',
  getNftActivity: 'getNftActivity',
  getUserCollections: 'getUserCollections',
  getCollectionType: 'getCollectionType',
  getUserTokenNumber: 'getUserTokenNumber',
  getUser1155Nfts: 'getUser1155Nfts',
  getPopularNFTs: 'getPopularNFTs',
  getAuctionNFTs: 'getAuctionNFTs',
  getFavorite: 'getFavorite',
  getFavNFT1155: 'getFavNFT1155',
  getIsUserExist:'getIsUserExist'
}
