import Head from 'next/head'

import Hero from '../components/sections/Hero'

import type { NextPageWithLayout } from './_app'

const Home: NextPageWithLayout = () => {
  return (
    <div className="bg-gradient-to-r from-dark_mild to-dark_heavy">
      <Head>
        <title>NGM Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
      </main>
    </div>
  )
}

Home.Layout = 'home'

export default Home
